### ISSUE TITLE
not running

### ISSUE THREAD

**Issue by anindya14** [kleiton0x00/ppmap#1]
Downloaded the precompiled binary and tried running ppmap but gave "permission denied"

When I tried with sudo it says "command not found"

**Comment by kleiton0x00** [comment]
After you download it make sure to give it the right permission by executing on terminal:
```chmod +x ppmap```  
Then execute it as following:  
```echo 'https://target.com' | ./ppmap```

**Comment by anindya14** [comment]
(facepalm) how can I not see that...
