### ISSUE TITLE
Not working in one VPS

### ISSUE THREAD

**Issue by marcelo321** [kleiton0x00/ppmap#14]
I wanted to know if you maybe know a workaround this. I sucesfully tried the tool and it worked  in 2 of my VPS, but in one of them it fails, it goes throw all the "requests" pretty fast and gives "erro" in all of them.

```
echo https://tomnomnom.uk/pp/?page=foo | ppmap
                                                                                 
    dMMMMb  dMMMMb  dMMMMMMMMb  .aMMMb  dMMMMb     v1.2.0
   dMP.dMP dMP.dMP dMP"dMP"dMP dMP"dMP dMP.dMP 
  dMMMMP" dMMMMP" dMP dMP dMP dMMMMMP dMMMMP"  
 dMP     dMP     dMP dMP dMP dMP dMP dMP           
dMP     dMP     dMP dMP dMP dMP dMP dMP            @kleiton0x7e

                                     
2022/08/19 05:26:10 [ERRO] https://tomnomnom.uk/pp/?page=foo&constructor%5Bprototype%5D%5Bppmap%5D=reserved
2022/08/19 05:26:10 [ERRO] https://tomnomnom.uk/pp/?page=foo&__proto__.ppmap=reserved
2022/08/19 05:26:10 [ERRO] https://tomnomnom.uk/pp/?page=foo&constructor.prototype.ppmap=reserved
2022/08/19 05:26:10 [ERRO] https://tomnomnom.uk/pp/?page=foo&__proto__%5Bppmap%5D=reserved
```

I successfully installed the requisites and chrome but something (I don't know what) fails when I run it. I updated everything and might be something I am unaware of.

Any idea what I can do to debug what's failing?

**Comment by kleiton0x00** [comment]
I haven't used ppmap in any VPS so I don't really know what the issue might be. Since you tried 2 VPSs and 1 one of them worked, I assume it has do be with the other VPS and not ppmap itself. Can you please provide me with more information about the faulty VPS? Maybe you have setup a proxy or sth?

**Comment by kleiton0x00** [comment]
Closing the issue due to long inactivity.
