### ISSUE TITLE
大佬 是无损扫描吗

### ISSUE THREAD

**Issue by pwnhxl** [kleiton0x00/ppmap#15]
大佬 是无损扫描吗？

**Comment by kleiton0x00** [comment]
English please?

**Comment by pwnhxl** [comment]
Whether the scan will cause the DOS OR server to crash or the OR service is unavailable

Can it be used in production environment

**Comment by pwnhxl** [comment]
@kleiton0x00

**Comment by kleiton0x00** [comment]
Of course it doesn't crash the server. Feel free to scan as much as you want.

**Comment by pwnhxl** [comment]
thank
