### ISSUE TITLE
Use existing chrome installation without installing it again.

### ISSUE THREAD

**Issue by Thy-GoD** [kleiton0x00/ppmap#16]
Burpsuite already installs chromium, would it be possible to use that instead of reinstalling chromium?

**Comment by kleiton0x00** [comment]
Yes, that is possible as well. In order to confirm that ppmap works as intended, you can try it out with some [demo targets](https://github.com/kleiton0x00/ppmap#demo)

**Comment by Thy-GoD** [comment]
> Yes, that is possible as well. In order to confirm that ppmap works as intended, you can try it out with some [demo targets](https://github.com/kleiton0x00/ppmap#demo)

I'm not sure how, I've tried it but it'd just fail, only way to make it work was to install chromium again.
