### ISSUE TITLE
Idea: use js-library-detector for broader gadgets detection

### ISSUE THREAD

**Issue by lirantal** [kleiton0x00/ppmap#3]
There's an npm project at https://www.npmjs.com/package/js-library-detector which provides code/library that you can run to detect which libraries exist on the page. Very similar to the gadgets detection that you referenced in the https://gist.github.com/nikitastupin/b3b64a9f8c0eb74ce37626860193eaec snippet.

**Comment by kleiton0x00** [comment]
Thank you for the suggestion, will definitely add this in my TO-DO list. More gadget detection = more XSS :)
