### ISSUE TITLE
Error on running

### ISSUE THREAD

**Issue by hellofresh01** [kleiton0x00/ppmap#7]
c:\go\src\github.com\chromedp\cdproto\page (from $GOROOT)
        C:\Users\Yaseen\go\src\github.com\chromedp\cdproto\page (from $GOPATH)
..\..\..\..\go\src\github.com\chromedp\chromedp\browser.go:18:2: cannot find package "github.com/chromedp/cdproto/runtime" in any of:
        c:\go\src\github.com\chromedp\cdproto\runtime (from $GOROOT)
        C:\Users\Yaseen\go\src\github.com\chromedp\cdproto\runtime (from $GOPATH)
..\..\..\..\go\src\github.com\chromedp\chromedp\browser.go:19:2: cannot find package "github.com/chromedp/cdproto/target" in any of:
        c:\go\src\github.com\chromedp\cdproto\target (from $GOROOT)
        C:\Users\Yaseen\go\src\github.com\chromedp\cdproto\target (from $GOPATH)
..\..\..\..\go\src\github.com\chromedp\chromedp\conn.go:9:2: cannot find package "github.com/gobwas/ws" in any of:
        c:\go\src\github.com\gobwas\ws (from $GOROOT)
        C:\Users\Yaseen\go\src\github.com\gobwas\ws (from $GOPATH)
..\..\..\..\go\src\github.com\chromedp\chromedp\conn.go:10:2: cannot find package "github.com/gobwas/ws/wsutil" in any of:
        c:\go\src\github.com\gobwas\ws\wsutil (from $GOROOT)
        C:\Users\Yaseen\go\src\github.com\gobwas\ws\wsutil (from $GOPATH)
..\..\..\..\go\src\github.com\chromedp\chromedp\browser.go:13:2: cannot find package "github.com/mailru/easyjson" in any of:
        c:\go\src\github.com\mailru\easyjson (from $GOROOT)
        C:\Users\Yaseen\go\src\github.com\mailru\easyjson (from $GOPATH)
..\..\..\..\go\src\github.com\chromedp\chromedp\conn.go:11:2: cannot find package "github.com/mailru/easyjson/jlexer" in any of:
        c:\go\src\github.com\mailru\easyjson\jlexer (from $GOROOT)
        C:\Users\Yaseen\go\src\github.com\mailru\easyjson\jlexer (from $GOPATH)
..\..\..\..\go\src\github.com\chromedp\chromedp\conn.go:12:2: cannot find package "github.com/mailru/easyjson/jwriter" in any of:
        c:\go\src\github.com\mailru\easyjson\jwriter (from $GOROOT)
        C:\Users\Yaseen\go\src\github.com\mailru\easyjson\jwriter (from $GOPATH)

I am getting this error on building.
 i have chromium installed

**Comment by kleiton0x00** [comment]
Have you installed Golang?

**Comment by hellofresh01** [comment]
Yes , golang is installed

**Comment by kleiton0x00** [comment]
Seems like you haven't installed **chromedp** properly, try executing the following command on cmd **AS ADMINISTRATOR**: ```go get -u github.com/chromedp/chromedp```
Then install Chromium/ Chrome (if you have it already installed, skip this step)
And then hopefully you will be able to compile it yourself without errors: ```go build ppmap.go```

You can also avoid building the software by downloading the precompiled one: https://github.com/kleiton0x00/ppmap/releases/download/v1.1.3/ppmap

**Comment by kleiton0x00** [comment]
Closing the issue due to long inactivity.
