### ISSUE TITLE
fix the readme.md , please

### ISSUE THREAD

**Issue by sv-atoslav** [kleiton0x00/ppmap#8]
cite of your readme:
![image](https://user-images.githubusercontent.com/28783346/136201554-0e1338db-49d7-499b-a5c9-466821ca5696.png)
I hope, an error is obviously:
![image](https://user-images.githubusercontent.com/28783346/136201351-0b220a3a-6f70-4128-9ee3-7d175459967f.png)

**Comment by kleiton0x00** [comment]
Thank you for submitting the issue, the README is updated with the valid command to install Chromium
